# Generated by Django 5.0.4 on 2024-05-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name_plural': 'Servicios'},
        ),
        migrations.AddField(
            model_name='servicios',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
