# Generated by Django 5.0.4 on 2024-04-29 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=200, verbose_name='Email')),
                ('contacto_telefonico', models.IntegerField(max_length=20, verbose_name='Teléfono movil')),
            ],
        ),
    ]
