# Generated by Django 5.0.4 on 2024-04-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contacto_telefonico',
            field=models.IntegerField(verbose_name='Teléfono movil'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
    ]
