# Generated by Django 5.0.4 on 2024-05-23 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_contacto_telefonico_and_more'),
        ('eventos', '0001_initial'),
        ('servicios', '0002_alter_servicios_options_servicios_avatar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterField(
            model_name='eventos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.servicios', verbose_name='Servicio a realizar'),
        ),
    ]
